{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-toolkit.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    # Attach your IAM role for Secrets Manager access (IRSA), e.g.:
    # eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT>:role/<ROLE>
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
